typedef struct espaco Espaco;
typedef Espaco* Tabuleiro;
typedef struct assam* Assam;
typedef struct lista* Jogadores;
typedef struct jogadorOf jogadorOf;
typedef struct elementoListaJogadores* ListaJogadores;
int dado();
Assam* criarAssam();
void setPosAssam(Assam*, Espaco*);
int moverAssam(Assam*, int,Tabuleiro*);
int putTapete(Tabuleiro*, Assam*, int, int, Jogadores*, struct jogadorOf*);
int updateInfo(ListaJogadores*, struct jogadorOf*, Assam*, int*);
void printInicio();
void diceAnim();
DWORD WINAPI passo(LPVOID);
DWORD WINAPI putTap(LPVOID);
DWORD WINAPI dice(LPVOID);
